import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "../globals.css";

import { cn } from "@/lib/utils";
import TopSideBar from "@/components/layouts/TopSideBar";
import LeftSideBar from "@/components/layouts/LeftSideBar";
import { ClerkProvider } from "@clerk/nextjs";
import { ToastProvider } from "@/lib/ToastProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased w-full",
            fontSans.variable
          )}
        >
          <ToastProvider />
          <TopSideBar />
          <div className="flex">
            <LeftSideBar />
            <div className="w-full container mx-auto my-10">{children}</div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
